### ISSUE TITLE
获取当前时间function报错function.name:不能为空

### ISSUE THREAD

**Issue by nygula** [AIDotNet/Thor#65]
* 描述: * 
当执行一个调用function的对话时.提示
code:1214,message:tools[0].function.name:不能为空

* 代码 *
```
using System.ComponentModel;
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.Connectors.OpenAI;

var kernelBuilder = Kernel.CreateBuilder()
    .AddOpenAIChatCompletion("gpt-4.1-mini", new Uri("https://api.token-ai.cn/v1"),
        "您的密钥");

kernelBuilder.Plugins.AddFromType<TimeInformation>();

var kernel = kernelBuilder.Build();

// 用提示符调用SK，要求AI提供它无法提供的信息，并可能产生幻觉
Console.WriteLine(await kernel.InvokePromptAsync("离圣诞节还有几天？"));

OpenAIPromptExecutionSettings settings = new() { FunctionChoiceBehavior = FunctionChoiceBehavior.Auto() };

// 用提示符调用内核，并允许AI自动调用函数
Console.WriteLine(await kernel.InvokePromptAsync("离圣诞节还有几天？解释你的想法", new(settings)));

class TimeInformation
{
    [KernelFunction]
    [Description("获取当前时间帮助用户解决时区不准确。")]
    public string GetCurrentUtcTime() => DateTime.UtcNow.ToString("R");
}




``` 

* 版本 *
 aidotnet/thor:latest   367c0e422144

* 部署脚本 * 
```

services:
  thor:
    image: aidotnet/thor:latest
    ports:
      - 18080:8080
    container_name: thor
    volumes:
      - ./data:/data
    environment:
      - TZ=Asia/Shanghai
      - DBType=sqlite # sqlite | [postgresql,pgsql] | [sqlserver,mssql] | mysql
      - ConnectionStrings:DefaultConnection=data source=/data/token.db
      - ConnectionStrings:LoggerConnection=data source=/data/logger.db
      - RunMigrationsAtStartup=true

```
