### ISSUE TITLE
星火大模型渠道测试失败

### ISSUE THREAD

**Issue by nygula** [AIDotNet/Thor#66]
* 版本 * 
thor                aidotnet/thor       latest              be159f525a7b        419MB

* docker compose 脚本 * 
```
[root@code thor]# cat docker-compose.yml
services:
  thor:
    image: aidotnet/thor:latest
    ports:
      - 18080:8080
    container_name: thor
    volumes:
      - ./data:/data
    environment:
      - TZ=Asia/Shanghai
      - DBType=sqlite # sqlite | [postgresql,pgsql] | [sqlserver,mssql] | mysql
      - ConnectionStrings:DefaultConnection=data source=/data/token.db
      - ConnectionStrings:LoggerConnection=data source=/data/logger.db
      - RunMigrationsAtStartup=true
     
```

* 复现方式 * 

1. 添加一个渠道 "星火大模型"
2. 填写 appid|appkey|appsecure
3. 模型选择 x1
4. 启用
5. 点击测试  
6. 报错 "Invalid URI: The hostname could not be parsed." 

* 浏览器报错信息 * 

请求网址:
http://192.168.0.75:18080/api/v1/channel/test/cc1597d0-6e94-4c53-ab8f-dbefca7ca54b
请求方法:
PUT
状态代码:
200 OK

{"message":"Invalid URI: The hostname could not be parsed.","success":false}
